server:
  tomcat:
    max-swallow-size: 10MB
  port: 8050
spring:
  servlet:
    multipart:
      max-file-size: 10MB  
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: microservices
    password: microservices
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
cloudinary:
  cloud_name: 
  api_key: 
  api_secret: 